name: Cinematicas
author: Joel
version: 0.3
api-version: 1.18
main: com.pyronixstudios.cinematicas.CinematicasMain
description: Plugin que te permite crear y cargar cinematicas.
commands:
    cinematicas:
        description: Este comando permite crear y cargar cinematics
        usage: /cinematicas crear/cargar nombre
    